# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.0
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError('Python 2.7 or later required')

# Import the low-level C/C++ module
if __package__ or '.' in __name__:
    from . import _AllocationFunctions
else:
    import _AllocationFunctions

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if name == "thisown":
        return self.this.own(value)
    if name == "this":
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if not static:
        object.__setattr__(self, name, value)
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if name == "thisown":
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)



def initialize():
    return _AllocationFunctions.initialize()

def Pointer_To_NumPy(p, size):
    return _AllocationFunctions.Pointer_To_NumPy(p, size)

def Pointer_To_NumPy_Int(p, size):
    return _AllocationFunctions.Pointer_To_NumPy_Int(p, size)

def Pointer_To_NumPy_Array(p, size1, size2):
    return _AllocationFunctions.Pointer_To_NumPy_Array(p, size1, size2)

def Pointer_To_NumPy_Array_Int(p, size1, size2):
    return _AllocationFunctions.Pointer_To_NumPy_Array_Int(p, size1, size2)

def File(strng):
    return _AllocationFunctions.File(strng)

def allocate_vector(SIZE):
    return _AllocationFunctions.allocate_vector(SIZE)

def allocate_int_vector(SIZE):
    return _AllocationFunctions.allocate_int_vector(SIZE)

def allocate_string(SIZE):
    return _AllocationFunctions.allocate_string(SIZE)

def reallocate_vector(p, SIZE):
    return _AllocationFunctions.reallocate_vector(p, SIZE)

def reallocate_int_vector(p, SIZE):
    return _AllocationFunctions.reallocate_int_vector(p, SIZE)

def reallocate_string(p, SIZE):
    return _AllocationFunctions.reallocate_string(p, SIZE)

def allocate_array(SIZE1, SIZE2):
    return _AllocationFunctions.allocate_array(SIZE1, SIZE2)

def allocate_array_int(SIZE1, SIZE2):
    return _AllocationFunctions.allocate_array_int(SIZE1, SIZE2)

def write_vector(z, i, value):
    return _AllocationFunctions.write_vector(z, i, value)

def write_array(z, i, j, value):
    return _AllocationFunctions.write_array(z, i, j, value)

def read_vector(z, i):
    return _AllocationFunctions.read_vector(z, i)

def read_array(z, i, j):
    return _AllocationFunctions.read_array(z, i, j)

def get_array_pointer(z, i):
    return _AllocationFunctions.get_array_pointer(z, i)

def get_array_pointer_int(z, i):
    return _AllocationFunctions.get_array_pointer_int(z, i)


